spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: aa
    url: jdbc:h2:mem:app
    password: appdb
  h2:
    console:
      enabled: 'true'
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
